[AJOUT] ajout d'un system de sauvegarde des statistiques du joueur
ServerOpenMC/Plugin pull request #354
Opened 2024-08-08 19:50 UTC by aure31

*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*:
oui
*Votre code se compile t-il en local ?*: 
oui
*Avez-vous supprimez les imports inutilisés ?*: 
oui
## Decrivez vos changements

Création d'une enum Stats.StatList qui permet de créer aisément des statistiques
personnalisées pour le joueur (ex : nombre de proute, nombre de morts, nombre de kills, etc.)
et de les incrémenter facilement avec la méthode add dans StatsManager.
*Clairement et avec des screenshots si nécessaires*

2024-08-08 20:02 UTC, llextv requested changes
Tu as clear le systeme de reports (tables ?) DatabaseManager.java:56 ?
`        this.getConnection().prepareStatement("CREATE TABLE `reports` (`sender` text NOT NULL,`reported` text NOT NULL,`reason` text NOT NULL,`timestamp` timestamp NOT NULL)");`

2024-08-08 20:15 UTC, AxenoDev commented
Le ChatGPT ....

2024-08-08 20:18 UTC, aure31 commented
juste pour les verifier si la colone exister dans la db si cela pose un problème j'aimerais connaitre lequel ?

2024-08-08 20:20 UTC, AxenoDev commented
On ne dev pas avec ChatGPT

2024-08-08 20:25 UTC, aure31 commented
D'accord, j'éviterai la prochaine fois. Mais j'ai vérifié le code, et il utilise le même système pour vérifier si une colonne existe que le système de gestion de l'argent pour vérifier si un joueur est déjà inscrit. Donc, je ne pense pas que cela pose problème ici. S'il y en a un, je souhaite sincèrement m'excuser.

2024-08-08 20:26 UTC, AxenoDev commented
Je ne peux pas accepter un code fait avec ChatGPT qui n'est pas très propres

2024-08-08 20:27 UTC, sajiterre commented
> D'accord, j'éviterai la prochaine fois. Mais j'ai vérifié le code, et il utilise le même système pour vérifier si une colonne existe que le système de gestion de l'argent pour vérifier si un joueur est déjà inscrit. Donc, je ne pense pas que cela pose problème ici. S'il y en a un, je souhaite sincèrement m'excuser.

Sa m'étonnerait que se soit accepté

2024-08-08 20:29 UTC, aure31 commented
comment ça il est pas propre je viens de dire que j'utilise le meme moyen que le system de money est ce que le system de money n'est pas propre ? ou j'ai manquer quelque chose ?

2024-08-08 20:31 UTC, aure31 commented
ou surment c'est mon code qui n'est pas propre pouvez vous me renseigner sur la partie qui n'est pas propre ?

2024-08-08 21:24 UTC, aure31 commented
operationelle maintenant (sans chatGPT pour vos plus grand plaisir)

2024-08-08 21:32 UTC, AxenoDev commented
et c'est pour faire quoi ?

2024-08-08 21:33 UTC, aure31 commented
Un système de statistiques (exemple stocker le nombre de proute)

2024-08-08 21:34 UTC, AxenoDev commented
pourquoi faire ??? a part sur charger la db ?

2024-08-08 21:35 UTC, AxenoDev commented
et ne pas utiliser ChatGPT veux dire aussi de pas copier le code des quests

2024-08-08 21:36 UTC, aure31 commented
Bas j'ai beaucoup de gens avait demander un système de statistiques donc c'est que j'ai fait ce sont que des nombre donc ça vas et j'ai optimiser les appels à la db et c'est un sorte de lybrary

2024-08-08 21:40 UTC, AxenoDev commented
mais ? C'est inutile car tu ne l'utilise nulle part

2024-08-08 21:46 UTC, aure31 commented
Le code dans lequel je l'utilise n'est pas finit et c'est aussi pour permettre au autres développeurs de l'utiliser si besoin.

2024-08-08 21:49 UTC, AxenoDev commented
bah fini le ?

2024-08-08 21:57 UTC, Fnafgameur commented
### J'ai jamais vu un code aussi propre.

![image](https://github.com/user-attachments/assets/95656dbd-0fa3-4b27-b429-d3cab6bc8095)

2024-08-08 21:58 UTC, aure31 commented
Oui mais je préfère d'abord le pull pour éviter que quelqu'un face le même système.
Et il est marqué de faire plusieurs petit pull qu'un gros donc j'ai crue que se serait mieux de d'abord pull ça. Aussi comme je l'ai expliqué le but est que ça soit utiliser par les autres dev si besoin pour leur propre système.

2024-08-08 21:59 UTC, aure31 commented
> ### J'ai jamais vu un code aussi propre.
> ![image](https://private-user-images.githubusercontent.com/82394539/356393412-95656dbd-0fa3-4b27-b429-d3cab6bc8095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNTQ1NjcsIm5iZiI6MTcyMzE1NDI2NywicGF0aCI6Ii84MjM5NDUzOS8zNTYzOTM0MTItOTU2NTZkYmQtMGZhMy00YjI3LWI0MjktZDNjYWI2YmM4MDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDIxNTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhM2E0ZDg3ZGVmMmZmODNmMzc2OTFhYzgwNDhjMWZjNWFkZTdlOTFkY2U1NjEyN2M3OWNkMGExMTI4M2ExN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O2yDJvt2i5cpUc6JiyvVvH-Z6mDdU5cf8TwUBNGuxgE)

C'est du troll ?
Car sinon c'est normal je début le dev.

2024-08-08 23:09 UTC, Fnafgameur commented
> > ### J'ai jamais vu un code aussi propre.
> > ![image](https://private-user-images.githubusercontent.com/82394539/356393412-95656dbd-0fa3-4b27-b429-d3cab6bc8095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNTQ1NjcsIm5iZiI6MTcyMzE1NDI2NywicGF0aCI6Ii84MjM5NDUzOS8zNTYzOTM0MTItOTU2NTZkYmQtMGZhMy00YjI3LWI0MjktZDNjYWI2YmM4MDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDIxNTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhM2E0ZDg3ZGVmMmZmODNmMzc2OTFhYzgwNDhjMWZjNWFkZTdlOTFkY2U1NjEyN2M3OWNkMGExMTI4M2ExN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O2yDJvt2i5cpUc6JiyvVvH-Z6mDdU5cf8TwUBNGuxgE)
> 
> C'est du troll ? Car sinon c'est normal je débute en dev.

Je taquine un coup, par contre, je veux bien que tu débutes en dev, mais ne te contente pas de copier-coller bêtement qqch sans comprendre ce que ça fait. J'ai aussi l'impression que tu n'es pas vraiment encore familiarisé avec le Java, je te conseillerai de suivre des petits tutos et de faire des petits programmes en Java pur pour t'entraîner et bien comprendre le langage.

2024-08-08 23:32 UTC, aure31 commented
Non tkt j'ai très bien compris ce que j'ai copier coller car ça marche comme se que j'avais fait mais divisé en différentes méthodes. Et pour ce qui est du java j'ai un bon niveau ne t'inquiète pas.

2024-08-09 20:08 UTC, aure31 commented
Alors ?

2024-08-11 11:02 UTC, closed without merging