Update ProutCommand.java - Casser le bateau lors du /prout
ServerOpenMC/Plugin pull request #356
Opened 2024-08-09 09:00 UTC by llextv

*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*:
Oui
*Votre code se compile t-il en local ?*: 
Oui
*Avez-vous supprimez les imports inutilisés ?*: 
Oui
## Decrivez vos changements
*Clairement et avec des screenshots si nécessaires*
J'ai refet la pull requests pour le /prout qui détruit les bateau et qui drop le bateau en fonction du type

2024-08-09 13:14 UTC, MathiasDPX requested changes
Dans `PasFraisListener.java` tu petes aussi

2024-08-09 13:14 UTC, MathiasDPX commented on src/main/java/fr/communaywen/core/commands/fun/ProutCommand.java
> +                player.getWorld().dropItemNaturally(player.getLocation(), itemBoat);
Utilise boat.getLocation()

2024-08-09 13:14 UTC, MathiasDPX commented on src/main/java/fr/communaywen/core/commands/fun/ProutCommand.java
> +    private Material getBoatType(Boat boat){
[Boat.Type#getMaterial()](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Boat.Type.html#getMaterial())

2024-08-10 11:20 UTC, llextv commented on src/main/java/fr/communaywen/core/commands/fun/ProutCommand.java
> +                player.getWorld().dropItemNaturally(player.getLocation(), itemBoat);
Cela ne change rien, si les personne était dans le bateau et que le bateau casse, l'item ira au meme endroit :/

2024-08-10 11:21 UTC, llextv commented on src/main/java/fr/communaywen/core/commands/fun/ProutCommand.java
> +    private Material getBoatType(Boat boat){
J'ai tester et j'ai essayer de compiler mais sa se compile pas donc j'ai mit sa

2024-08-12 14:14 UTC, llextv commented
ducoup ?

2024-08-15 01:01 UTC, MathiasDPX commented
Sync ta branche

2024-08-15 10:27 UTC, llextv commented
C'était deja fait mais puisque sa fait 1semaine que j'ai ouvert cet pull c'est juste normal

2024-08-16 18:45 UTC, merged