Feature/builder wand
ServerOpenMC/Plugin pull request #374
Opened 2024-08-12 13:21 UTC by Fnafgameur

*Avez-vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*: *Oui*

*Votre code se compile-t-il en local ?*: *Oui*

*Avez-vous supprimé les imports inutilisés ?*: *Oui*
# Décrivez vos changements
# ⚠️ A merge APRÈS #399 (hammer rework) si approbation de la PR (je me chargerais de régler les conflits)⚠️
Ajout du `Builder Wand` permettant de poser une large zone d'un même type de bloc si le joueur en possède sur lui.
Le rayon peut être manuellement modifié dans `customitems.yml` (par défaut : 4).

## Builder Wand
![image](https://github.com/user-attachments/assets/153d1c19-6cfc-4e23-b29b-87b98a582dd9)
![image](https://github.com/user-attachments/assets/ada072e2-736f-47bb-9d8b-7e81bd12185a)

## Le rayon d'action (par défaut)
![image](https://github.com/user-attachments/assets/97e628af-f5a8-4613-a7d4-591d9d5334fc)

2024-08-12 18:41 UTC, Meekiavelique commented
Stylé !

2024-08-13 11:23 UTC, Margouta commented
Il y a qq chose à ajouter du côté ItemsAdder ?

2024-08-13 12:10 UTC, Fnafgameur commented
> Il y a qq chose à ajouter du côté ItemsAdder ?

Yep, mais j'attends un petit fix de la texture de la part de _BGIO_ avant de te l'envoyer

2024-08-14 14:10 UTC, Margouta commented
Ok, je merge plus tard

2024-08-15 02:21 UTC, Fnafgameur commented
> Sync ta branche

C'est good

2024-08-15 11:12 UTC, MathiasDPX commented
Et envoie le pack itemsadder

2024-08-15 14:09 UTC, Fnafgameur commented
> Et envoie le pack itemsadder

Déjà envoyé à Margouta

2024-08-16 18:52 UTC, MathiasDPX commented
Si j'ai pas le pack je pourrais pas le mettre sur le serveur de dev

2024-08-16 20:45 UTC, Fnafgameur commented
> Si j'ai pas le pack je pourrais pas le mettre sur le serveur de dev

Ok, quel est ton pseudo discord ?

2024-08-16 20:46 UTC, ri1ongithub commented
gyro3630

2024-08-16 20:47 UTC, sajiterre commented
> > Si j'ai pas le pack je pourrais pas le mettre sur le serveur de dev
> 
> Ok, quel est ton pseudo discord ?

Nan faut envoyer a qlq qui a l'accès pour qu'il l'ajoute

2024-08-16 20:47 UTC, sajiterre commented
> gyro3630
Incroyable se pseudo

2024-08-16 20:47 UTC, llextv commented
oula il se build pas

2024-08-16 20:48 UTC, ri1ongithub commented
Pourquoi t'as retiré des imports utilisés ? :grocervo:

2024-08-16 20:49 UTC, llextv commented
![image](https://github.com/user-attachments/assets/2e71cf14-5be9-499e-b628-6eb3ed2f791f)
sa vient de la

2024-08-16 20:49 UTC, llextv commented
retire pas PotionEffect, PotionEffectType ni PotionMeta

2024-08-16 20:50 UTC, Fnafgameur commented
> Pourquoi t'as retiré des imports utilisés ? :grocervo:

Alors, y'avait un conflit avec la master, mais j'ai pas retiré d'imports, je check ça.

2024-08-16 20:51 UTC, llextv requested changes
Tu as suprimés des imports utilisé, c'est la cause du build fail

2024-08-16 20:51 UTC, llextv commented on src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> -import org.bukkit.inventory.meta.PotionMeta;
Import utilisé delete

2024-08-16 20:51 UTC, llextv commented on src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> -import org.bukkit.potion.PotionEffect;
Import utilisé delete

2024-08-16 20:51 UTC, llextv commented on src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> -import org.bukkit.potion.PotionEffectType;
Import utilisé delete

2024-08-16 20:54 UTC, llextv commented
Ok

2024-08-16 20:56 UTC, Fnafgameur commented
My bad j'avais oublié de remettre mon import

2024-08-16 21:51 UTC, MathiasDPX commented
> > gyro3630
> > Incroyable se pseudo

pourquoi mdr

2024-08-16 21:53 UTC, sajiterre commented
> > > gyro3630
> > > Incroyable se pseudo
> 
> pourquoi mdr

Tu connais pas le 3630 ?

2024-08-17 10:09 UTC, MathiasDPX commented
> > > > gyro3630
> > > > Incroyable se pseudo
> > 
> > 
> > pourquoi mdr
> 
> Tu connais pas le 3630 ?

Bah si ._.

2024-08-22 18:54 UTC, Fnafgameur commented
J'ai réglé les derniers soucis de conflits avec la master.

2024-08-23 20:47 UTC, misieur commented
> > > > gyro3630
> > > > Incroyable se pseudo
> > 
> > pourquoi mdr
> 
> Tu connais pas le 3630 ?

Je savait même pas

2024-08-24 02:07 UTC, Fnafgameur commented
# ⚠️Merge cette PR APRÈS #399 (hammer rework) si approbation de la PR (je me chargerais de régler les conflits)⚠️

2024-08-30 09:56 UTC, MathiasDPX commented
Je suis en train de review :)

2024-08-30 10:02 UTC, MathiasDPX commented
Les marteaux sont beaucoup trop résistant
Celui en netherite est incassable
On peut pas les réparer
- En mettant un marteau dans une enclume on le dupe

2024-09-01 17:20 UTC, MathiasDPX approved these changes

2024-09-01 17:20 UTC, merged