Evènement pour Halloween sur OpenMC
ServerOpenMC/Plugin pull request #479
Opened 2024-10-29 10:46 UTC by Nocolm

*Avez vous lu le [Code de Conduite](https://github.com/Margouta/PluginOpenMC/blob/main/CODE_OF_CONDUCT.md)?*: oui

*Votre code se compile t-il en local ?*: oui

*Avez-vous supprimez les imports inutilisés ?*: oui ( normalement )
## Decrivez vos changements 
*Clairement et avec des screenshots si nécessaires*
J'ai coder un évènement pour halloween rajoutant : une dimension temporaire ou il y a un manoir / une lootbox pour halloween / des "hats" ( chapeaux ) / des bonbons / un shop hebdomadaire et un shop de bonbon accessible par une commande / ( pour les modos une commande pour désactiver l'événement au cas où) / des drops customs pour les mobs dans le manoir / une nouvelle quête hebdomadaire .

2024-10-29 10:53 UTC, MathiasDPX commented
Tu as laissé des debugs

2024-10-29 10:55 UTC, iambibi requested changes
Attention ma review est plutot vide, je conseille qu'un autre developpeur dise ce qu'il en pense

2024-10-29 10:55 UTC, iambibi commented on src/main/java/fr/communaywen/core/evenements/EventsCommand.java
> +            player.sendMessage(ChatColor.RED + "Aucun évenement en cours revenez plus tard");
Mets comme ça tes messages,

`MessageManager.sendMessageType(getOwner(), "Message", Prefix.CONTEST, MessageType.SUCCESS, true);` 
Ton prefix est def dans fr.communaywen.core.utils.constant.Prefix

2024-10-29 10:55 UTC, iambibi commented on src/main/java/fr/communaywen/core/evenements/WeeklyItemType.java
> +    WeeklyItemType(String itemType, String itemName, String displayName, String material, int data, int cost, String money, String moneyName,String lore, int enchant_level){
Essaie d'avoir un ItemStack + cost + money + moneyName + namespace item adder

2024-10-29 10:55 UTC, iambibi commented on src/main/java/fr/communaywen/core/evenements/menus/EventsWeeklyShop.java
> +    private void GiveItems(Player player, ItemStack item){
GiveItems => giveItems

2024-10-29 10:56 UTC, iambibi commented
> Tu as laissé des debugs Il y as besoin d'un pack ia ? Pourquoi je suis collaborateur dans la cmd évents ?

- Il y a un menu custom
- Il a repris le systeme de la dimension des reves

2024-10-29 11:00 UTC, iambibi commented on src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> +        Bukkit.getConsoleSender().sendMessage("Le WeeklyItemType a été charger : " + getConfig().getString("weekly-item"));
Euh tu as rien rajouter dans le config.yml?

2024-10-29 11:18 UTC, Nocolm commented on src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> +        Bukkit.getConsoleSender().sendMessage("Le WeeklyItemType a été charger : " + getConfig().getString("weekly-item"));
Si ....

2024-10-29 11:19 UTC, Nocolm commented on src/main/java/fr/communaywen/core/evenements/EventsCommand.java
> +            player.sendMessage(ChatColor.RED + "Aucun évenement en cours revenez plus tard");
ok je vais voir ça

2024-10-29 11:19 UTC, Nocolm commented on src/main/java/fr/communaywen/core/evenements/menus/EventsWeeklyShop.java
> +    private void GiveItems(Player player, ItemStack item){
ok.

2024-10-29 11:20 UTC, iambibi commented on src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> +        Bukkit.getConsoleSender().sendMessage("Le WeeklyItemType a été charger : " + getConfig().getString("weekly-item"));
![Screenshot_20241029_121932_Chrome](https://github.com/user-attachments/assets/54458bfa-dee3-4d86-b374-bab6323e9011)

2024-10-29 11:20 UTC, iambibi commented on src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> +        Bukkit.getConsoleSender().sendMessage("Le WeeklyItemType a été charger : " + getConfig().getString("weekly-item"));
Non.

2024-10-29 11:20 UTC, Nocolm commented
> Tu as laissé des debugs Il y as besoin d'un pack ia ? Pourquoi je suis collaborateur dans la cmd évents ?

Mince je pensais les avoir tous retirer

2024-10-29 11:23 UTC, Nocolm commented on src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> +        Bukkit.getConsoleSender().sendMessage("Le WeeklyItemType a été charger : " + getConfig().getString("weekly-item"));
mais normalement si ? 
![image](https://github.com/user-attachments/assets/45863d21-1d86-4515-a6ff-8031350b845f)

2024-10-29 11:33 UTC, Nocolm commented on src/main/java/fr/communaywen/core/evenements/WeeklyItemType.java
> +    WeeklyItemType(String itemType, String itemName, String displayName, String material, int data, int cost, String money, String moneyName,String lore, int enchant_level){
hue pour les livres enchantés pas sûr que ça va marcher

2024-10-29 11:36 UTC, Nocolm commented on src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> +        Bukkit.getConsoleSender().sendMessage("Le WeeklyItemType a été charger : " + getConfig().getString("weekly-item"));
Regarde la class DataTime

2024-10-29 12:00 UTC, iambibi commented on src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> +        Bukkit.getConsoleSender().sendMessage("Le WeeklyItemType a été charger : " + getConfig().getString("weekly-item"));
Évite de mettre des espaces

2024-10-29 12:02 UTC, iambibi commented on src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> +        Bukkit.getConsoleSender().sendMessage("Le WeeklyItemType a été charger : " + getConfig().getString("weekly-item"));
Et non dans ton commit je vois pas un config.yml

2024-10-29 12:03 UTC, iambibi commented on src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> +        Bukkit.getConsoleSender().sendMessage("Le WeeklyItemType a été charger : " + getConfig().getString("weekly-item"));
Montre moi que j'ai tord.

2024-10-29 12:58 UTC, Nocolm commented on src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> +        Bukkit.getConsoleSender().sendMessage("Le WeeklyItemType a été charger : " + getConfig().getString("weekly-item"));
mais je viens de te montrer que c'est sauvegarder sur le config.yml du plugin je peux rien faire d'autre pour te le montrer

2024-10-29 13:43 UTC, iambibi commented on src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> +        Bukkit.getConsoleSender().sendMessage("Le WeeklyItemType a été charger : " + getConfig().getString("weekly-item"));
Si tu le dis on verra sur le serveur ptdr

2024-10-29 17:45 UTC, iambibi commented on src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> +        Bukkit.getConsoleSender().sendMessage("Le WeeklyItemType a été charger : " + getConfig().getString("weekly-item"));
![image](https://github.com/user-attachments/assets/1ff8367f-01c1-4c9a-8726-77e36a41fe1c)
tu vois ça devrais etre marqué dans les fichiers modifié

2024-10-29 19:22 UTC, Nocolm commented on src/main/java/fr/communaywen/core/AywenCraftPlugin.java
> +        Bukkit.getConsoleSender().sendMessage("Le WeeklyItemType a été charger : " + getConfig().getString("weekly-item"));
ba je sais pas parce que sur mon ide sa apparait pas mais quand j'ouvre le config.yml seul il est présent

2024-10-30 11:45 UTC, Nocolm commented
j'allais oublier pour la dim faut remplacer le fichier créer par celui_ci sinon le manoir ba il existe pas
[Mansion.zip](https://github.com/user-attachments/files/17571677/Mansion.zip)

2024-11-02 14:20 UTC, Nocolm commented
ducoup est-ce que c'est un code propre pour être ajouter au serveur ou pas ?

2024-11-02 15:48 UTC, Nocolm commented on src/main/java/fr/communaywen/core/quests/QuestsListener.java
> +    EnumSet<EntityType> MansionEntities = EnumSet.of(EntityType.ZOMBIE_VILLAGER, EntityType.SKELETON, EntityType.SPIDER, EntityType.CAVE_SPIDER, EntityType.WITHER_SKELETON, EntityType.VINDICATOR, Ent
normalement c'est corrigé

2025-01-16 22:02 UTC, closed without merging